version: '3.7'

services:
  web:
      container_name: web
      build: .
      command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./dailywheaterdigest:/src/:delegated
      ports:
        - "8000:8000"
      environment:
        - SECRET_KEY=${SECRET_KEY}
        - DEBUG=true