version: '3.7'

services:
  web:
    container_name: web
    build: .
    command: sh -c "python manage.py migrate && uvicorn dailywheaterdigest.asgi:application --host 0.0.0.0"
    volumes:
      - ./dailywheaterdigest:/src/:delegated
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=true
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    stdin_open: true
    tty: true